# Generated by Django 3.2.16 on 2022-12-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='type',
            field=models.CharField(choices=[(0, 'Seminar'), (1, 'Exhibition')], max_length=10),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='type',
            field=models.CharField(choices=[(0, 'Seminar'), (1, 'Exhibition')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='type',
            field=models.CharField(choices=[(0, 'Individual'), (1, 'Organization')], max_length=15),
        ),
    ]
