# Generated by Django 3.2.16 on 2022-12-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_author_books'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='seminarauthor',
            unique_together={('seminar', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='seminarsponsor',
            unique_together={('seminar', 'sponsor')},
        ),
    ]
