# Generated by Django 4.1.4 on 2022-12-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_auto_20221211_1645"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibition",
            name="type",
            field=models.CharField(
                choices=[("Seminar", "Seminar"), ("Exhibition", "Exhibition")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="seminar",
            name="type",
            field=models.CharField(
                choices=[("Seminar", "Seminar"), ("Exhibition", "Exhibition")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="type",
            field=models.CharField(
                choices=[
                    ("Individual", "Individual"),
                    ("Organization", "Organization"),
                ],
                max_length=15,
            ),
        ),
    ]
