# Generated by Django 4.1.4 on 2022-12-12 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0007_alter_copy_status_alter_payment_method_and_more"),
        ("events", "0003_alter_exhibition_type_alter_seminar_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seminarauthor",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="inventory.author"
            ),
        ),
        migrations.AlterField(
            model_name="seminarauthor",
            name="seminar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="events.seminar"
            ),
        ),
        migrations.AlterField(
            model_name="seminarsponsor",
            name="seminar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="events.seminar"
            ),
        ),
        migrations.AlterField(
            model_name="seminarsponsor",
            name="sponsor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="events.sponsor"
            ),
        ),
        migrations.CreateModel(
            name="ExhibitionUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exhibition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="events.exhibition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("exhibition", "user")},
            },
        ),
        migrations.AddField(
            model_name="exhibition",
            name="user",
            field=models.ManyToManyField(
                through="events.ExhibitionUser", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
