# Generated by Django 3.2.16 on 2022-12-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20221209_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.CharField(default='Dibner 3rd Floor', max_length=100),
            preserve_default=False,
        ),
    ]
