version: "3.8"

services:
  mysql-db:
    image: mysql:oracle
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysql -u root --password='$MYSQL_ROOT_PASSWORD' --execute 'SHOW DATABASES;'"
      interval: 10s
      timeout: 30s
      retries: 5

  web:
    build: .
    env_file: .env
    restart: always
    volumes:
      - .:/app/
    depends_on:
      - mysql-db
    working_dir: "/app/reallibrary"
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  mysql_data:
