# Generated by Django 4.1.3 on 2022-12-07 02:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=50)),
                ("street", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=2)),
                ("zipcode", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Copy",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        max_length=1,
                        validators=[django.core.validators.MinLengthValidator],
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="inventory.book",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(verbose_name="invoice date")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Rental",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=1)),
                ("borrow_date", models.DateField(verbose_name="borrowed date")),
                (
                    "expected_return",
                    models.DateField(verbose_name="expected return date"),
                ),
                ("actual_return", models.DateField(verbose_name="actual return date")),
                (
                    "copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="inventory.copy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(verbose_name="payment date")),
                (
                    "method",
                    models.CharField(
                        max_length=2,
                        validators=[django.core.validators.MinLengthValidator],
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.invoice",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="rental",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.rental"
            ),
        ),
        migrations.CreateModel(
            name="BookAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.author",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.book"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="inventory.topic"
            ),
        ),
        migrations.AddIndex(
            model_name="rental",
            index=models.Index(fields=["id"], name="inventory_r_id_438e13_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["id"], name="inventory_i_id_504d10_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="bookauthor",
            unique_together={("book", "author")},
        ),
    ]
