# Generated by Django 3.2.16 on 2022-12-11 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='state',
            field=models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='author',
            name='zipcode',
            field=models.IntegerField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='copy',
            name='status',
            field=models.CharField(choices=[(0, 'Available'), (1, 'Borrowed'), (2, 'Lost'), (3, 'Damaged')], max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[(0, 'Cash'), (1, 'Credit'), (2, 'Debit'), (3, 'PayPal')], max_length=10),
        ),
    ]
