# Generated by Django 3.2.16 on 2022-12-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(through='inventory.BookAuthor', to='inventory.Book'),
        ),
    ]
