# Generated by Django 3.2.16 on 2022-12-11 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20221211_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='zipcode',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
