# Generated by Django 4.1.3 on 2022-12-08 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_author_id_alter_book_id_alter_copy_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="copy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="inventory.copy",
            ),
        ),
    ]
