# Generated by Django 3.2.16 on 2022-12-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_author_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[(0, 'Borrowed'), (1, 'Returned'), (2, 'Overdue')], max_length=10),
        ),
    ]
