# Generated by Django 3.2.16 on 2022-12-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_rental_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='actual_return',
            field=models.DateField(blank=True, null=True, verbose_name='actual return date'),
        ),
    ]
