# Generated by Django 4.1.4 on 2022-12-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_rental_copy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copy",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Borrowed", "Borrowed"),
                    ("Lost", "Lost"),
                    ("Damaged", "Damaged"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Credit", "Credit"),
                    ("Debit", "Debit"),
                    ("PayPal", "PayPal"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="status",
            field=models.CharField(
                choices=[
                    ("Borrowed", "Borrowed"),
                    ("Returned", "Returned"),
                    ("Overdue", "Overdue"),
                ],
                max_length=10,
            ),
        ),
    ]
