# Generated by Django 4.1.4 on 2022-12-12 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_customer_identity_type"),
        ("inventory", "0007_alter_copy_status_alter_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="home.customer",
            ),
            preserve_default=False,
        ),
    ]
