# Generated by Django 4.1.4 on 2022-12-12 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0008_rental_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rental",
            name="customer",
        ),
        migrations.AddField(
            model_name="rental",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
