# Generated by Django 4.1.4 on 2022-12-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_customer_identity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="identity_type",
            field=models.CharField(
                choices=[
                    ("Passport", "Passport"),
                    ("SSN", "SSN"),
                    ("Driver's License", "Driver's License"),
                ],
                max_length=20,
            ),
        ),
    ]
